language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "travis_retry pip install nose"
  - "travis_retry pip install git+git://github.com/TurboGears/sprox.git@development"
  - "travis_retry pip install git+git://github.com/TurboGears/tg2.git@development"
  - "travis_retry pip install git+git://github.com/TurboGears/tgext.crud.git"

script: "python setup.py nosetests"
